#!/bin/bash
#PBS -l nodes=10:ppn=12,walltime=00:05:00
#PBS -q batch
#PBS -N run_mandelOmpMpi
#PBS -j oe
#PBS -V

cd ~/assignments/A9
export OMP_NUM_THREADS=6;

mpiexec -np 10 --map-by ppr:1:node --hostfile $PBS_NODEFILE mandelbrot.cx
mpiexec -np 5 --map-by ppr:1:node --hostfile $PBS_NODEFILE mandelbrot.cx
mpiexec -np 3 --map-by ppr:1:node --hostfile $PBS_NODEFILE mandelbrot.cx
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE mandelbrot.cx