#!/bin/bash
#PBS -l nodes=1:ppn=12,walltime=00:05:00
#PBS -q batch
#PBS -N run_mandelSerial
#PBS -j oe
#PBS -V

cd ~/mandelbrot/serial
#mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE mandelbrot.cx
./mandelbrot.cx