#!/bin/bash
#PBS -l nodes=6:ppn=12,walltime=00:01:30
#PBS -q batch
#PBS -N COMP3450_A4
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/assignments/A4
mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./result