#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:00:10
#PBS -q batch
#PBS -N send_receive_int
#PBS -j oe

#cat $PBS_NODEFILE
cd ~/assignments/A2/
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mpi_a