#!/bin/bash
#PBS -l nodes=1:ppn=12, walltime=00:01:00
#PBS -q batch
#PBS -N COMP3450_A3
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/assignments/A5
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./A5