#!/bin/bash
#PBS -l nodes=5:ppn=12,walltime=00:05:00
#PBS -q batch
#PBS -N COMP3450_A6
#PBS -j oe
#PBS -V

cd ~/assignments/A6_2
mpiexec -np 5 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./A6parallel_starter.cx